{{- if .Values.jmeter.sfagent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring.fullname" . }}-sfagent-jmeter
  labels:
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    snappyflow/component: jmeter
data:
  config.yaml: |+
    ---
    key: "{{ .Values.global.key }}"
    logging:
      plugins:
      - name: jmeter
        enabled: true
        config:
          log_path: "/var/log/test_plan.jtl"
{{- end }}