{{- if .Values.ingress.enabled -}}
{{- $fullName := include "spring.fullname" . }}
{{- $httpPort := .Values.service.httpPort }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ template "spring.name" . }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    snappyflow/component: petclinic
  name: {{ template "spring.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  rules:
  - http:
      paths:
      - path: /{{ template "spring.name" . }}
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $httpPort }}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
