{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "spring.controller.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "spring.name" . }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    snappyflow/component: petclinic
spec:
  selector:
    matchLabels:
      app: {{ template "spring.name" . }}
      heritage: "{{ .Release.Service }}"
      release: "{{ .Release.Name }}"
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}
