{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "archival-kafka-connect.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "archival-kafka-connect.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageValue: "850m"
  - type: External
    external:
      metricName: kafka_bytesinpersec_oneminuterate_for_log_and_metric
      targetValue: {{ mul .Values.autoscaling.ingestRateGBPerDayPerPod 11575 }}
{{- end }}
