# Default values for sf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
monitor:
  image:
    repository: ahmed3465/monitor
    tag: v1
    pullPolicy: IfNotPresent
  containerResources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 10Mi

jobserver:
  image:
    repository: ahmed3465/jobserver
    tag: v6
    pullPolicy: IfNotPresent
  serverPort: 5002
  service:
    servicePort: 5002
  sparkProperties:
    logDirectory: sparkhs/spark-hs
  containerResources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 50Mi

infrastructure:
  Kubernetes:
    enabled: false
    image: snappyflowml/spark-compact-aws:beta
    preference: 1
    cluster: "k8s://kubernetes.default.svc:443"
    numExecutors: 5
    jobResources:
      cpu:
        requests:
          executor: 0.2
          driver: 0.2
        limits:
          executor: 0.4
          driver: 0.5
      memory:
        executor: 1024m
        driver: 1024m
  EcsFargate:
    enabled: true
    image: ahmed3465/spark-on-fargate:v10
    preference: 2
    cluster: sf-archival-compaction
    numExecutors: 2
    iamRole: arn:aws:iam::159750416379:role/Dev-Archival-presto_hive
    taskSubnet: subnet-09a6fcdc2b614e300
    taskSecurityGroup: sg-03b8db147f1b7b423
    jobResources:
      cpu: 2048
      memory: 8192

nameOverride: ""

fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}
